### ISSUE TITLE
Unable to install/configure ZFS on ubuntu (EC2 AMI)

### ISSUE THREAD

**Issue by jayfk** [ClusterHQ/unofficial-flocker-tools#28]
Stacktrace:

```
configure: error: in `/var/lib/dkms/spl/0.6.4.2/build':
configure: error: C compiler cannot create executables
See `config.log' for more details
Error! Bad return status for module build on kernel: 3.13.0-48-generic (x86_64)
Consult /var/lib/dkms/spl/0.6.4.2/build/make.log for more information.
configure: error:
*** Please make sure the kmod spl devel <kernel> package for your
*** distribution is installed then try again.  If that fails you
*** can specify the location of the spl objects with the
*** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: 3.13.0-48-generic (x86_64)
Consult /var/lib/dkms/zfs/0.6.4.2/build/make.log for more information.
Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.
Traceback (most recent call last):
  File "/Users/j/dev/.virtualenvs/flocker/bin/flocker-install", line 9, in <module>
load_entry_point('UnofficialFlockerTools==0.3', 'console_scripts', 'flocker-install')()
  File "/Users/j/dev/.virtualenvs/flocker/lib/python2.7/site-packages/unofficial_flocker_tools/install.py", line 52, in main
""")
  File "/Users/j/dev/.virtualenvs/flocker/lib/python2.7/site-packages/unofficial_flocker_tools/utils.py", line 17, in runSSH
return subprocess.check_output(command, shell=True)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'ssh -o LogLevel=error -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/foo.pem root@bar.com sh -c 'echo installing-zfs
add-apt-repository -y ppa:zfs-native/stable
apt-get update
apt-get -y --force-yes install libc6-dev zfsutils
mkdir -p /var/opt/flocker
truncate --size 10G /var/opt/flocker/pool-vdev
zpool create flocker /var/opt/flocker/pool-vdev
'' returned non-zero exit status 1
```

**Comment by lukemarsden** [comment]
Hi @jayfk - thanks for trying this out and I'm sorry you had trouble with it. Which AMI exactly did you use? Was this Ubuntu 14.04? We'll try to reproduce the problem and get back to you.
