### ISSUE TITLE
errors while running CLI commands

### ISSUE THREAD

**Issue by wallnerryan** [ClusterHQ/unofficial-flocker-tools#55]
Fresh install of uft. Getting:

```
wallnerryan@mac:-> flockerctl --control-service=ec2-54-183-210-219.us-west-1.compute.amazonaws.com list-nodes
Unhandled Error
Traceback (most recent call last):
  File "/opt/flocker/bin/flockerctl", line 9, in <module>
    load_entry_point('UnofficialFlockerTools==0.6', 'console_scripts', 'flockerctl')()
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 364, in _main
    react(main, sys.argv[1:])
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/task.py", line 875, in react
    finished = main(_reactor, *argv)
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 344, in main
    d = defer.maybeDeferred(base.subOptions.run)
--- <exception caught here> ---
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 140, in maybeDeferred
    result = f(*args, **kw)
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 87, in run
    self.client = get_client(self.parent)
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 48, in get_client
    target_hostname=control_service,
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/txflocker/client.py", line 172, in get_client
    user_crt, cluster_crt, user_key, target_hostname))
exceptions.Exception: Not enough information to construct TLS context: user_crt: FilePath('/pwd/user.crt'), cluster_crt: FilePath('/pwd/cluster.crt'), user_key: FilePath('/pwd/user.key'), target_hostname: ec2-54-183-210-219.us-west-1.compute.amazonaws.com
main function encountered error
Traceback (most recent call last):
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/task.py", line 875, in react
    finished = main(_reactor, *argv)
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 355, in main
    d.addErrback(err)
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 318, in addErrback
    errbackKeywords=kw)
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 296, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/flocker/local/lib/python2.7/site-packages/unofficial_flocker_tools/flocker_volumes.py", line 354, in err
    reactor.stop()
  File "/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/base.py", line 580, in stop
    "Can't stop reactor that isn't running.")
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
```

**Comment by wallnerryan** [comment]
This is because `DOCKER_HOST` was set to another working `DOCKER_HOST` but not the local one. Fixed by re-running `eval` on local docker-machine host. No real error to figure this out, but its not a real issue, rather a user issue ;). Closing
